### ISSUE TITLE
There seems to be rounding errors

### ISSUE THREAD

**Issue by SeeTwoDev** [StefanKunde/TradeMaster_POE#24]
It appears there is some errors, especially toward the end of results sets.
I was going for vaals and while it started at 19c up to 26... when i got to 27 it went down to 20 and a dude thought i was trying to scam him.

PS: the app says 1.3 instead of 1.4

**Comment by veenarm** [comment]
CurrencyOffer.java

Change everything to be doubles instead of 'ints' (except for the amount you want.

Then modify the tradeMessager to something like the below..

`
    public void generateTradeMessage(double wantedAmount) {
        double priceForAll = wantedAmount * pricePerUnit;
        String priceTextForAll;

        if (priceForAll % 1 == 0) {
            priceTextForAll = String.valueOf((int) priceForAll);
        } else {
            DecimalFormat df = new DecimalFormat("####0.0");
            df.setRoundingMode(RoundingMode.CEILING);
            priceTextForAll = df.format(priceForAll);
        }
`

_This outputs the messages to be purchase order of 5._
1x <- 4.5 x Chaos :: Hi, I'd like to buy your 5 Pristine Fossil for my 22.5 chaos in Betrayal.
1x <- 4.8333 x Chaos :: Hi, I'd like to buy your 5 Pristine Fossil for my 24.2 chaos in Betrayal.
1x <- 5 x Chaos :: Hi, I'd like to buy your 5 Pristine Fossil for my 25 chaos in Betrayal.

**Comment by StefanKunde** [comment]
@veenarm Did you implement this in your latest PR?
